spring.application.name=goldenticket2


# Server
server.port=${SERVER_PORT:8080}

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/golden_ticket?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Bogota}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

# JWT
app.jwt.secret=${JWT_SECRET:Z29sZGVuLXRpY2tldC1kZXZlbG9wbWVudC1zZWNyZXQtMzItYnl0ZXMtbWluaW11bQ==}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}

# Ticket PDF storage
app.ticket.storage-path=${TICKET_STORAGE_PATH:tickets}

# Wompi Sandbox
app.wompi.base-url=${WOMPI_BASE_URL:https://sandbox.wompi.co/v1}
app.wompi.public-key=${WOMPI_PUBLIC_KEY:pub_prod_0YBynxLK8YEAZUkOyPkTlo5WtdGgwZpa}
app.wompi.private-key=${WOMPI_PRIVATE_KEY:prv_prod_AxVFYti5H1zKlIjfimmjjk95mmKECWIO}
app.wompi.events-secret=${WOMPI_EVENTS_SECRET:prod_events_YKksa9UQYE1I8oSQ23JQr9nxK1aMBT5j}
app.wompi.integrity-secret=${WOMPI_INTEGRITY_SECRET:prod_integrity_8wA9VRooB3oiPIy9aGdL5johIV9m2Fad}
app.wompi.redirect-url=${WOMPI_REDIRECT_URL:http://localhost:8080/api/payments/redirect}

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/v3/api-docs

# Logging
logging.level.com.example.goldenticket2=INFO